name: MCSMigrationManager
version: 1.1.1
main: com.gradyn.McsMigrationManager.McsMigrationManager
api-version: 1.19

permissions:
  mcsmgr.transfer:
    description: Allows a user to transfer historical users to a real user.
    default: op
  mcsmgr.acceptrules:
    description: Allows a user to use /acceptrules
    default: false
  mcsmgr.archive:
    description: Allows a user to visit archived plots via /archive
    default: false

commands:
  transfer:
    description: Transfer a historical user to a real user
    usage: "/nebulous (historical user) (real user)"
    permission: mcsmgr.transfer
  acceptrules:
    description: Accept the rules and become a constructor
    usage: "/acceptrules"
    permission: mcsmgr.acceptrules
  archive:
    description: teleport to an archive plot
    usage: "/archive (historical username)"
    permission: mcsmgr.archive